// 海克斯大乱斗数据 - 从 arammayhem.com 获取
// 更新时间: 2026-06-04

// 英雄数据
const champions = [
  { id: 1, name: "复仇焰魂", nameEn: "brand", tags: ["法师"], winrate: 55.15, iconId: "63", winrate: 55.15 },
  { id: 2, name: "疾风剑豪", nameEn: "yasuo", tags: ["战士"], winrate: 56.0, iconId: "157", winrate: 56.0 },
  { id: 3, name: "堕落天使", nameEn: "morgana", tags: ["辅助"], winrate: 53.98, iconId: "25", winrate: 53.98 },
  { id: 4, name: "祖安狂人", nameEn: "drmundo", tags: ["坦克"], winrate: 53.49, iconId: "36", winrate: 53.49 },
  { id: 5, name: "法外狂徒", nameEn: "graves", tags: ["射手"], winrate: 52.74, iconId: "104", winrate: 52.74 },
  { id: 6, name: "德邦总管", nameEn: "xinzhao", tags: ["战士"], winrate: 53.72, iconId: "5", winrate: 53.72 },
  { id: 7, name: "暗夜猎手", nameEn: "vayne", tags: ["射手"], winrate: 52.48, iconId: "67", winrate: 52.48 },
  { id: 8, name: "暴走萝莉", nameEn: "jinx", tags: ["射手"], iconId: "222", winrate: 53.6 },
  { id: 9, name: "含羞蓓蕾", nameEn: "lillia", tags: ["战士"], iconId: "876", winrate: 58.96 },
  { id: 10, name: "腕豪", nameEn: "sett", tags: ["战士"], winrate: 52.75, iconId: "875", winrate: 52.75 },
  { id: 11, name: "皮城女警", nameEn: "caitlyn", tags: ["射手"], winrate: 51.51, iconId: "51", winrate: 51.51 },
  { id: 12, name: "铸星龙王", nameEn: "aurelionsol", tags: ["法师"], winrate: 52.23, iconId: "136", winrate: 52.23 },
  { id: 13, name: "死亡颂唱者", nameEn: "karthus", tags: ["法师"], winrate: 51.91, iconId: "30", winrate: 51.91 },
  { id: 14, name: "虚空先知", nameEn: "malzahar", tags: ["法师"], winrate: 54.01, iconId: "90", winrate: 54.01 },
  { id: 15, name: "圣枪游侠", nameEn: "lucian", tags: ["射手"], winrate: 50.74, iconId: "236", winrate: 50.74 },
  { id: 16, name: "封魔剑魂", nameEn: "yone", tags: ["战士"], winrate: 53.45, iconId: "777", winrate: 53.45 },
  { id: 17, name: "赏金猎人", nameEn: "missfortune", tags: ["射手"], winrate: 50.55, iconId: "21", winrate: 50.55 },
  { id: 18, name: "卡牌大师", nameEn: "twistedfate", tags: ["法师"], winrate: 53.18, iconId: "4", winrate: 53.18 },
  { id: 19, name: "影流之镰", nameEn: "kayn", tags: ["战士"], winrate: 53.36, iconId: "141", winrate: 53.36 },
  { id: 20, name: "镕铁少女", nameEn: "rell", tags: ["坦克"], winrate: 54.42, iconId: "526", winrate: 54.42 },
  { id: 21, name: "正义巨像", nameEn: "galio", tags: ["坦克"], winrate: 52.8, iconId: "3", winrate: 52.8 },
  { id: 22, name: "符文法师", nameEn: "ryze", tags: ["法师"], iconId: "13", winrate: 50.69 },
  { id: 23, name: "无极剑圣", nameEn: "masteryi", tags: ["战士"], iconId: "11", winrate: 51.5 },
  { id: 24, name: "不破之誓", nameEn: "yunara", tags: ["射手"], winrate: 52.13, iconId: "804", winrate: 52.13 },
  { id: 25, name: "星籁歌姬", nameEn: "seraphine", tags: ["辅助"], winrate: 56.16, iconId: "147", winrate: 56.16 },
  { id: 26, name: "河流之王", nameEn: "tahmkench", tags: ["坦克"], winrate: 50.73, iconId: "223", winrate: 50.73 },
  { id: 27, name: "战争之影", nameEn: "hecarim", tags: ["战士"], winrate: 51.35, iconId: "120", winrate: 51.35 },
  { id: 28, name: "机械公敌", nameEn: "rumble", tags: ["战士"], winrate: 53.07, iconId: "68", winrate: 53.07 },
  { id: 29, name: "正义天使", nameEn: "kayle", tags: ["法师"], winrate: 52.91, iconId: "10", winrate: 52.91 },
  { id: 30, name: "寒冰射手", nameEn: "ashe", tags: ["射手"], winrate: 49.41, iconId: "22", winrate: 49.41 },
  { id: 31, name: "涤魂圣枪", nameEn: "senna", tags: ["辅助"], iconId: "235", winrate: 49.72 },
  { id: 32, name: "异画师", nameEn: "hwei", tags: ["法师"], iconId: "910", winrate: 53.97 },
  { id: 33, name: "诺克萨斯统领", nameEn: "swain", tags: ["法师"], iconId: "50", winrate: 50.16 },
  { id: 34, name: "荆棘之兴", nameEn: "zyra", tags: ["法师"], winrate: 53.59, iconId: "143", winrate: 53.59 },
  { id: 35, name: "九尾妖狐", nameEn: "ahri", tags: ["法师"], iconId: "103", winrate: 52.83 },
  { id: 36, name: "炼金术士", nameEn: "singed", tags: ["坦克"], iconId: "27", winrate: 51.29 },
  { id: 37, name: "远古巫灵", nameEn: "xerath", tags: ["法师"], winrate: 51.13, iconId: "101", winrate: 51.13 },
  { id: 38, name: "虚空之女", nameEn: "kaisa", tags: ["射手"], iconId: "145", winrate: 49.1 },
  { id: 39, name: "亡灵战神", nameEn: "sion", tags: ["坦克"], iconId: "14", winrate: 52.82 },
  { id: 40, name: "邪恶小法师", nameEn: "veigar", tags: ["法师"], winrate: 50.4, iconId: "45", winrate: 50.4 },
  { id: 41, name: "逆羽", nameEn: "xayah", tags: ["射手"], winrate: 50.87, iconId: "498", winrate: 50.87 },
  { id: 42, name: "扭曲树精", nameEn: "maokai", tags: ["坦克"], winrate: 51.02, iconId: "57", winrate: 51.02 },
  { id: 43, name: "奥术先驱", nameEn: "viktor", tags: ["法师"], winrate: 52.76, iconId: "112", winrate: 52.76 },
  { id: 44, name: "影流之主", nameEn: "zed", tags: ["刺客"], winrate: 50.02, iconId: "238", winrate: 50.02 },
  { id: 45, name: "潮汐海灵", nameEn: "fizz", tags: ["刺客"], winrate: 49.68, iconId: "105", winrate: 49.68 },
  { id: 46, name: "英勇投弹手", nameEn: "corki", tags: ["射手"], winrate: 51.09, iconId: "42", winrate: 51.09 },
  { id: 47, name: "蛮族之王", nameEn: "tryndamere", tags: ["战士"], winrate: 50.75, iconId: "23", winrate: 50.75 },
  { id: 48, name: "双界灵兔", nameEn: "aurora", tags: ["法师"], winrate: 52.28, iconId: "893", winrate: 52.28 },
  { id: 49, name: "瘟疫之源", nameEn: "twitch", tags: ["射手"], winrate: 49.17, iconId: "29", winrate: 49.17 },
  { id: 50, name: "虚空之眼", nameEn: "velkoz", tags: ["法师"], winrate: 51.69, iconId: "161", winrate: 51.69 },
  { id: 51, name: "暗黑元首", nameEn: "syndra", tags: ["法师"], winrate: 51.74, iconId: "134", winrate: 51.74 },
  { id: 52, name: "迅捷斥候", nameEn: "teemo", tags: ["射手"], winrate: 49.03, iconId: "17", winrate: 49.03 },
  { id: 53, name: "炽炎雏龙", nameEn: "smolder", tags: ["射手"], iconId: "901", winrate: 48.39 },
  { id: 54, name: "德玛西亚之力", nameEn: "garen", tags: ["战士"], iconId: "86", winrate: 48.36 },
  { id: 55, name: "麦林炮手", nameEn: "tristana", tags: ["射手"], winrate: 49.01, iconId: "18", winrate: 49.01 },
  { id: 56, name: "光辉女郎", nameEn: "lux", tags: ["法师"], winrate: 50.16, iconId: "99", winrate: 50.16 },
  { id: 57, name: "时间刺客", nameEn: "ekko", tags: ["刺客"], winrate: 51.45, iconId: "245", winrate: 51.45 },
  { id: 58, name: "戏命师", nameEn: "jhin", tags: ["射手"], winrate: 47.95, iconId: "202", winrate: 47.95 },
  { id: 59, name: "深海泰坦", nameEn: "nautilus", tags: ["坦克"], winrate: 49.89, iconId: "111", winrate: 49.89 },
  { id: 60, name: "山隐之焰", nameEn: "ornn", tags: ["坦克"], iconId: "516", winrate: 50.46 },
  { id: 61, name: "虚空恐惧", nameEn: "chogath", tags: ["坦克"], iconId: "31", winrate: 48.39 },
  { id: 62, name: "未来守护者", nameEn: "jayce", tags: ["战士"], iconId: "126", winrate: 47.03 },
  { id: 63, name: "德玛西亚皇子", nameEn: "jarvaniv", tags: ["战士"], winrate: 48.47, iconId: "59", winrate: 48.47 },
  { id: 64, name: "永猎双子", nameEn: "kindred", tags: ["射手"], iconId: "203", winrate: 51.15 },
  { id: 65, name: "深渊巨口", nameEn: "kogmaw", tags: ["射手"], winrate: 50.27, iconId: "96", winrate: 50.27 },
  { id: 66, name: "不落魔锋", nameEn: "zaahen", tags: ["战士"], iconId: "904", winrate: 52.89 },
  { id: 67, name: "爆破鬼才", nameEn: "ziggs", tags: ["法师"], iconId: "115", winrate: 49.71 },
  { id: 68, name: "暮光之眼", nameEn: "shen", tags: ["坦克"], winrate: 50.84, iconId: "98", winrate: 50.84 },
  { id: 69, name: "武器大师", nameEn: "jax", tags: ["战士"], winrate: 50.09, iconId: "24", winrate: 50.09 },
  { id: 70, name: "曙光女神", nameEn: "leona", tags: ["坦克"], winrate: 50.19, iconId: "89", winrate: 50.19 },
  { id: 71, name: "大发明家", nameEn: "heimerdinger", tags: ["法师"], winrate: 52.04, iconId: "74", winrate: 52.04 },
  { id: 72, name: "流光镜影", nameEn: "mel", tags: ["法师"], iconId: "800", winrate: 48.27 },
  { id: 73, name: "惩戒之箭", nameEn: "varus", tags: ["射手"], iconId: "110", winrate: 48.31 },
  { id: 74, name: "龙血武姬", nameEn: "shyvana", tags: ["战士"], iconId: "102", winrate: 51.17 },
  { id: 75, name: "灵罗娃娃", nameEn: "gwen", tags: ["战士"], iconId: "887", winrate: 53.52 },
  { id: 76, name: "熔岩巨兽", nameEn: "malphite", tags: ["坦克"], iconId: "54", winrate: 47.4 },
  { id: 77, name: "海洋之灾", nameEn: "gangplank", tags: ["战士"], winrate: 49.19, iconId: "41", winrate: 49.19 },
  { id: 78, name: "探险家", nameEn: "ezreal", tags: ["射手"], winrate: 47.14, iconId: "81", winrate: 47.14 },
  { id: 79, name: "残月之肃", nameEn: "aphelios", tags: ["射手"], winrate: 51.13, iconId: "523", winrate: 51.13 },
  { id: 80, name: "牛头酋长", nameEn: "alistar", tags: ["坦克"], winrate: 49.03, iconId: "12", winrate: 49.03 },
  { id: 81, name: "时光守护者", nameEn: "zilean", tags: ["辅助"], winrate: 50.28, iconId: "26", winrate: 50.28 },
  { id: 82, name: "狂厄蔷薇", nameEn: "briar", tags: ["战士"], winrate: 52.04, iconId: "233", winrate: 52.04 },
  { id: 83, name: "远古恐惧", nameEn: "fiddlesticks", tags: ["法师"], iconId: "9", winrate: 50.35 },
  { id: 84, name: "北地之怒", nameEn: "sejuani", tags: ["坦克"], winrate: 50.0, iconId: "113", winrate: 50.0 },
  { id: 85, name: "不屈之枪", nameEn: "pantheon", tags: ["战士"], iconId: "80", winrate: 49.15 },
  { id: 86, name: "诺克萨斯之手", nameEn: "darius", tags: ["战士"], winrate: 47.33, iconId: "122", winrate: 47.33 },
  { id: 87, name: "解脱者", nameEn: "sylas", tags: ["法师"], iconId: "517", winrate: 47.88 },
  { id: 88, name: "愁云使者", nameEn: "vex", tags: ["法师"], iconId: "711", winrate: 51.15 },
  { id: 89, name: "战争女神", nameEn: "sivir", tags: ["射手"], iconId: "15", winrate: 49.03 },
  { id: 90, name: "血港鬼影", nameEn: "pyke", tags: ["辅助"], iconId: "555", winrate: 48.98 },
  { id: 91, name: "破败之王", nameEn: "viego", tags: ["战士"], winrate: 49.92, iconId: "234", winrate: 49.92 },
  { id: 92, name: "无双剑姬", nameEn: "fiora", tags: ["战士"], iconId: "114", winrate: 51.6 },
  { id: 93, name: "虚空行者", nameEn: "kassadin", tags: ["刺客"], iconId: "38", winrate: 50.22 },
  { id: 94, name: "恶魔小丑", nameEn: "shaco", tags: ["刺客"], iconId: "35", winrate: 46.43 },
  { id: 95, name: "猩红收割者", nameEn: "vladimir", tags: ["法师"], iconId: "8", winrate: 48.5 },
  { id: 96, name: "刀锋之影", nameEn: "talon", tags: ["刺客"], winrate: 49.68, iconId: "91", winrate: 49.68 },
  { id: 97, name: "铁血狼母", nameEn: "ambessa", tags: ["战士"], iconId: "799", winrate: 50.71 },
  { id: 98, name: "影哨", nameEn: "akshan", tags: ["射手"], iconId: "166", winrate: 50.36 },
  { id: 99, name: "炼金男爵", nameEn: "renata", tags: ["辅助"], iconId: "888", winrate: 52.52 },
  { id: 100, name: "风暴之怒", nameEn: "janna", tags: ["辅助"], iconId: "40", winrate: 52.12 },
  { id: 101, name: "蒸汽机器人", nameEn: "blitzcrank", tags: ["坦克"], iconId: "53", winrate: 46.93 },
  { id: 102, name: "铁铠冥魂", nameEn: "mordekaiser", tags: ["战士"], iconId: "82", winrate: 46.58 },
  { id: 103, name: "齐天大圣", nameEn: "monkeyking", tags: ["战士"], winrate: 48.25, iconId: "62", winrate: 48.25 },
  { id: 104, name: "海兽祭司", nameEn: "illaoi", tags: ["战士"], winrate: 49.14, iconId: "420", winrate: 49.14 },
  { id: 105, name: "放逐之刃", nameEn: "riven", tags: ["战士"], winrate: 49.56, iconId: "92", winrate: 49.56 },
  { id: 106, name: "殇之木乃伊", nameEn: "amumu", tags: ["坦克"], iconId: "32", winrate: 48.52 },
  { id: 107, name: "沙漠玫瑰", nameEn: "samira", tags: ["射手"], iconId: "360", winrate: 48.13 },
  { id: 108, name: "酒桶", nameEn: "gragas", tags: ["战士"], winrate: 49.06, iconId: "79", winrate: 49.06 },
  { id: 109, name: "不羁之悦", nameEn: "nilah", tags: ["战士"], winrate: 51.36, iconId: "895", winrate: 51.36 },
  { id: 110, name: "冰霜女巫", nameEn: "lissandra", tags: ["法师"], iconId: "127", winrate: 48.37 },
  { id: 111, name: "魂锁典狱长", nameEn: "thresh", tags: ["辅助"], iconId: "412", winrate: 45.7 },
  { id: 112, name: "发条魔灵", nameEn: "orianna", tags: ["法师"], winrate: 49.66, iconId: "61", winrate: 49.66 },
  { id: 113, name: "复仇之矛", nameEn: "kalista", tags: ["射手"], iconId: "429", winrate: 49.9 },
  { id: 114, name: "兽灵行者", nameEn: "udyr", tags: ["战士"], iconId: "77", winrate: 46.82 },
  { id: 115, name: "天启者", nameEn: "karma", tags: ["法师"], iconId: "43", winrate: 48.84 },
  { id: 116, name: "虚空掠夺者", nameEn: "khazix", tags: ["刺客"], winrate: 47.82, iconId: "121", winrate: 47.82 },
  { id: 117, name: "永恒梦魇", nameEn: "nocturne", tags: ["战士"], iconId: "56", winrate: 49.21 },
  { id: 118, name: "暗裔剑魔", nameEn: "aatrox", tags: ["战士"], iconId: "266", winrate: 45.39 },
  { id: 119, name: "琴瑟仙女", nameEn: "sona", tags: ["辅助"], winrate: 49.99, iconId: "37", winrate: 49.99 },
  { id: 120, name: "荣耀行刑官", nameEn: "draven", tags: ["射手"], iconId: "119", winrate: 47.99 },
  { id: 121, name: "众星之子", nameEn: "soraka", tags: ["辅助"], iconId: "16", winrate: 49.25 },
  { id: 122, name: "圣锤之毅", nameEn: "poppy", tags: ["坦克"], winrate: 48.85, iconId: "78", winrate: 48.85 },
  { id: 123, name: "皎月女神", nameEn: "diana", tags: ["战士"], winrate: 47.96, iconId: "131", winrate: 47.96 },
  { id: 124, name: "不灭狂雷", nameEn: "volibear", tags: ["战士"], winrate: 48.02, iconId: "106", winrate: 48.02 },
  { id: 125, name: "不祥之刃", nameEn: "katarina", tags: ["刺客"], winrate: 44.79, iconId: "55", winrate: 44.79 },
  { id: 126, name: "盲僧", nameEn: "leesin", tags: ["战士"], iconId: "64", winrate: 43.12 },
  { id: 127, name: "魔蛇之拥", nameEn: "cassiopeia", tags: ["法师"], iconId: "69", winrate: 48.35 },
  { id: 128, name: "岩雀", nameEn: "taliyah", tags: ["法师"], winrate: 49.27, iconId: "163", winrate: 49.27 },
  { id: 129, name: "唤潮鲛姬", nameEn: "nami", tags: ["辅助"], iconId: "267", winrate: 49.71 },
  { id: 130, name: "黑暗之女", nameEn: "annie", tags: ["法师"], iconId: "1", winrate: 49.2 },
  { id: 131, name: "德玛西亚之翼", nameEn: "quinn", tags: ["射手"], winrate: 47.67, iconId: "133", winrate: 47.67 },
  { id: 132, name: "明烛", nameEn: "milio", tags: ["辅助"], winrate: 49.36, iconId: "902", winrate: 49.36 },
  { id: 133, name: "巨魔之王", nameEn: "trundle", tags: ["战士"], winrate: 45.14, iconId: "48", winrate: 45.14 },
  { id: 134, name: "沙漠死神", nameEn: "nasus", tags: ["战士"], iconId: "75", winrate: 47.04 },
  { id: 135, name: "狂野女猎手", nameEn: "nidalee", tags: ["刺客"], iconId: "76", winrate: 45.6 },
  { id: 136, name: "瓦洛兰之盾", nameEn: "taric", tags: ["辅助"], winrate: 49.08, iconId: "44", winrate: 49.08 },
  { id: 137, name: "傲之追猎者", nameEn: "rengar", tags: ["刺客"], iconId: "107", winrate: 46.98 },
  { id: 138, name: "魔法猫咪", nameEn: "yuumi", tags: ["辅助"], iconId: "350", winrate: 47.88 },
  { id: 139, name: "皮城执法官", nameEn: "vi", tags: ["战士"], winrate: 47.31, iconId: "254", winrate: 47.31 },
  { id: 140, name: "百裂冥犬", nameEn: "naafiri", tags: ["刺客"], winrate: 46.68, iconId: "950", winrate: 46.68 },
  { id: 141, name: "暮光星灵", nameEn: "zoe", tags: ["法师"], iconId: "142", winrate: 46.83 },
  { id: 142, name: "披甲龙龟", nameEn: "rammus", tags: ["坦克"], iconId: "33", winrate: 46.12 },
  { id: 143, name: "无畏战车", nameEn: "urgot", tags: ["战士"], iconId: "6", winrate: 45.81 },
  { id: 144, name: "沙漠皇帝", nameEn: "azir", tags: ["法师"], winrate: 47.57, iconId: "268", winrate: 47.57 },
  { id: 145, name: "弗雷尔卓德之心", nameEn: "braum", tags: ["坦克"], winrate: 48.02, iconId: "201", winrate: 48.02 },
  { id: 146, name: "冰晶凤凰", nameEn: "anivia", tags: ["法师"], winrate: 47.06, iconId: "34", winrate: 47.06 },
  { id: 147, name: "万花通灵", nameEn: "neeko", tags: ["法师"], iconId: "518", winrate: 46.53 },
  { id: 148, name: "仙灵女巫", nameEn: "lulu", tags: ["辅助"], iconId: "117", winrate: 47.81 },
  { id: 149, name: "狂暴之心", nameEn: "kennen", tags: ["法师"], winrate: 45.96, iconId: "85", winrate: 45.96 },
  { id: 150, name: "雪原双子", nameEn: "nunu", tags: ["坦克"], iconId: "20", winrate: 45.98 },
  { id: 151, name: "元素女皇", nameEn: "qiyana", tags: ["刺客"], iconId: "246", winrate: 46.97 },
  { id: 152, name: "虚空女皇", nameEn: "belveth", tags: ["战士"], winrate: 46.3, iconId: "200", winrate: 46.3 },
  { id: 153, name: "迷失之牙", nameEn: "gnar", tags: ["战士"], winrate: 44.7, iconId: "150", winrate: 44.7 },
  { id: 154, name: "虚空遁地兽", nameEn: "reksai", tags: ["战士"], winrate: 47.61, iconId: "421", winrate: 47.61 },
  { id: 155, name: "蜘蛛女皇", nameEn: "elise", tags: ["刺客"], winrate: 47.12, iconId: "60", winrate: 47.12 },
  { id: 156, name: "幻翎", nameEn: "rakan", tags: ["辅助"], iconId: "497", winrate: 46.71 },
  { id: 157, name: "上古领主", nameEn: "skarner", tags: ["坦克"], iconId: "72", winrate: 47.01 },
  { id: 158, name: "诡术妖姬", nameEn: "leblanc", tags: ["刺客"], iconId: "7", winrate: 43.35 },
  { id: 159, name: "翠神", nameEn: "ivern", tags: ["辅助"], winrate: 47.03, iconId: "427", winrate: 47.03 },
  { id: 160, name: "生化魔人", nameEn: "zac", tags: ["坦克"], winrate: 44.9, iconId: "154", winrate: 44.9 },
  { id: 161, name: "荒漠屠夫", nameEn: "renekton", tags: ["战士"], winrate: 44.21, iconId: "58", winrate: 44.21 },
  { id: 162, name: "祖安花火", nameEn: "zeri", tags: ["射手"], winrate: 44.88, iconId: "221", winrate: 44.88 },
  { id: 163, name: "祖安怒兽", nameEn: "warwick", tags: ["战士"], winrate: 45.41, iconId: "19", winrate: 45.41 },
  { id: 164, name: "离群之刺", nameEn: "akali", tags: ["刺客"], winrate: 43.7, iconId: "84", winrate: 43.7 },
  { id: 165, name: "暴怒骑士", nameEn: "kled", tags: ["战士"], winrate: 46.39, iconId: "240", winrate: 46.39 },
  { id: 166, name: "痛苦之拥", nameEn: "evelynn", tags: ["刺客"], winrate: 46.64, iconId: "28", winrate: 46.64 },
  { id: 167, name: "狂战士", nameEn: "olaf", tags: ["战士"], winrate: 45.64, iconId: "2", winrate: 45.64 },
  { id: 168, name: "牧魂人", nameEn: "yorick", tags: ["战士"], winrate: 46.13, iconId: "83", winrate: 46.13 },
  { id: 169, name: "纳祖芒荣耀", nameEn: "ksante", tags: ["坦克"], winrate: 42.49, iconId: "897", winrate: 42.49 },
  { id: 170, name: "刀锋舞者", nameEn: "irelia", tags: ["战士"], winrate: 42.92, iconId: "39", winrate: 42.92 },
  { id: 171, name: "青钢影", nameEn: "camille", tags: ["战士"], winrate: 44.25, iconId: "164", winrate: 44.25 },
  { id: 172, name: "星界游神", nameEn: "bard", tags: ["辅助"], winrate: 41.95, iconId: "432", winrate: 41.95 }
];

// 海克斯强化数据
const hexAugments = [
  { id: 1, name: "回归基本功", description: "回归基本功海克斯大乱斗强化符文攻略 - 你的终极技能已被封印。获得30%技能伤害、治疗效果、护盾，和60技能急速。 胜率：53.84%，登场率：8.37%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Back_To_Basics_mayhem_augment.webp" },
  { id: 2, name: "史上最大雪球", description: "史上最大雪球海克斯大乱斗强化符文攻略 - 你的雪球获得100技能急速。 你的雪球现在变得非常大，并且可以穿过小兵。它会对敌人造成持续2秒的20%减速， 将他们击飞0.75秒，并造成额外200-350(基于等级)(+100% 额外AD)(+ 60%AP)伤害。 如果你没有雪球，则获得一个雪球。…", tier: "prismatic", image: "https://arammayhem.com/augments/Biggest_Snowball_Ever_mayhem_augment.webp" },
  { id: 3, name: "利刃华尔兹", description: "利刃华尔兹海克斯大乱斗强化符文攻略 - 获得召唤师技能利刃华尔兹。 利刃华尔兹会让你进入不可被选取状态，在此期间对敌人进行反复突进并造成伤害。 胜率：48.29%，登场率：9.80%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Blade_Waltz_mayhem_augment.webp" },
  { id: 4, name: "魄罗之王的弹跳", description: "魄罗之王的弹跳海克斯大乱斗强化符文攻略 - 将一个召唤师技能替换为魄罗之王的弹跳！…", tier: "prismatic", image: "https://arammayhem.com/augments/Bounce_of_the_Poro_King_mayhem_augment.webp" },
  { id: 5, name: "你摸不到", description: "你摸不到海克斯大乱斗强化符文攻略 - 施放你的终极技能会使你进入持续无敌秒的的免疫伤害状态(冷却秒冷却时间)。 胜率：46.71%，登场率：4.32%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Cant_Touch_This_mayhem_augment.webp" },
  { id: 6, name: "地狱三头犬", description: "地狱三头犬海克斯大乱斗强化符文攻略 - 获得丛刃和强攻基石符文。 丛刃：对英雄的前三次普通攻击会获得140%/80%攻击速度 强攻：对同一英雄进行三次攻击会造成额外120-360 (基于等级)(+40%AD)(+30%AP) 自适应伤害，并提高15%后续伤害…", tier: "prismatic", image: "https://arammayhem.com/augments/Cerberus_mayhem_augment.webp" },
  { id: 7, name: "死亡之环", description: "死亡之环海克斯大乱斗强化符文攻略 - 你造成的治疗效果和生命回复效果会对相距最近的那个敌方英雄造成@HealToDamageConversion*100@%该治疗数额的魔法伤害。 胜率：50.69%，登场率：6.83%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Circle_of_Death_mayhem_augment.webp" },
  { id: 8, name: "小丑学院", description: "小丑学院海克斯大乱斗强化符文攻略 - 获得召唤师技能欺诈魔术：隐身最多3秒，并在0.125秒延迟后闪现到400单位内的目标位置。你的下一次普通攻击造成100（+150%额外AD）（+55%AP）额外物理伤害。…", tier: "prismatic", image: "https://arammayhem.com/augments/Clown_College_mayhem_augment.webp" },
  { id: 9, name: "巨像的勇气", description: "巨像的勇气海克斯大乱斗强化符文攻略 - 定身或缚地一个敌方英雄后获得100 – 300(基于等级)（+ 5%最大生命值）护盾值。 胜率：49.36%，登场率：8.77%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Courage_of_the_Colossus_mayhem_augment.webp" },
  { id: 10, name: "残忍", description: "残忍海克斯大乱斗强化符文攻略 - 定身或缚地一个敌方英雄时，召唤一颗彗星至敌人上方。彗星会在1秒后着陆，在区域内造成50-150(基于等级)(+ 40%AP)(+ 4%最大生命值)魔法伤害。 这个效果对每次技能施放和每个目标都有6秒冷却时间。…", tier: "prismatic", image: "https://arammayhem.com/augments/Cruelty_mayhem_augment.webp" },
  { id: 11, name: "全凭身法", description: "全凭身法海克斯大乱斗强化符文攻略 - 你的冲刺、跳跃、闪烁或传送类技能获得100技能急速。 胜率：50.31%，登场率：14.63%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Dashing_mayhem_augment.webp" },
  { id: 12, name: "你肩上的恶魔", description: "你肩上的恶魔海克斯大乱斗强化符文攻略 - 你已与【大魔王】本尊订立了一个契约，他每秒汲取你0.75%当前生命值，如果附近有敌人则提升至7.5%。…", tier: "prismatic", image: "https://arammayhem.com/augments/Devil_on_Your_Shoulder_mayhem_augment.webp" },
  { id: 13, name: "亮出你的剑", description: "亮出你的剑海克斯大乱斗强化符文攻略 - 变为近战状态，并且获得30%攻击力、30%生命值、25%攻击速度、20%生命偷取和25%移动速度 ，每个属性都基于舍弃的攻击距离提升0-30%（从500开始，每15提升3%）。 胜率：61.33%，登场率：11.97%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Draw_Your_Sword_mayhem_augment.webp" },
  { id: 14, name: "飞身踢", description: "飞身踢海克斯大乱斗强化符文攻略…", tier: "prismatic", image: "https://arammayhem.com/augments/Dropkick_mayhem_augment.webp" },
  { id: 15, name: "卡皮巴拉空投", description: "卡皮巴拉空投海克斯大乱斗强化符文攻略 - 获得召唤师技能卡皮巴拉空投。 在2秒后，一个卡皮巴拉撞进地面，造成25%最大生命值的真实伤害。 胜率：47.48%，登场率：5.75%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Droppybara_mayhem_augment.webp" },
  { id: 16, name: "双刀流", description: "双刀流海克斯大乱斗强化符文攻略 - 在你攻击时，发射一个次级弩箭，造成40%伤害和40%效能的命中。获得20%总攻击速度。 胜率：58.14%，登场率：29.11%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Dual_Wield_mayhem_augment.webp" },
  { id: 17, name: "信念者的强化", description: "信念者的强化海克斯大乱斗强化符文攻略 - 为友军提供治疗或护盾会赐福他们8秒。当被赐福的友军对敌方英雄造成伤害时，你会获得【虔诚】层数。在50层【虔诚】时，释放一道冲击波来造成50-300(基于等级)(+75000%治疗和护盾强度)伤害，并斩杀(25%治疗和护盾强度)的敌人。…", tier: "prismatic", image: "https://arammayhem.com/augments/Empowered_By_The_Faithful_mayhem_augment.webp" },
  { id: 18, name: "至高天诺言", description: "至高天诺言海克斯大乱斗强化符文攻略 - 获得15%治疗和护盾强度，获得至高天诺言召唤师技能。警惕传送至你的友军并在着陆时提供持续3秒的100 - 250(基于等级) +100%AP + 10%额外生命值护盾值。 胜率：48.03%，登场率：1.20%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Empyrean_Promise_mayhem_augment.webp" },
  { id: 19, name: "尤里卡", description: "尤里卡海克斯大乱斗强化符文攻略 - 获得相当于30%法术强度的技能急速。 胜率：58.41%，登场率：36.41%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Eureka_mayhem_augment.webp" },
  { id: 20, name: "连拨击锤", description: "连拨击锤海克斯大乱斗强化符文攻略 - 在你攻击时，发射5个额外箭矢，每个箭矢造成10–52.5（基于等级）(+15%额外AD)物理伤害。每个方向有独立的5秒冷却时间，且每个箭矢可以暴击造成200伤害并以20%效率触发命中效果。不会被小兵触发。…", tier: "prismatic", image: "https://arammayhem.com/augments/Fan_The_Hammer_mayhem_augment.webp" },
  { id: 21, name: "感受燃烧", description: "感受燃烧海克斯大乱斗强化符文攻略 - 获得召唤师技能感受灼烧。 感受灼烧会对所有附近的敌人们施放引燃和虚弱。 范围：800 胜率：49.34%，登场率：4.43%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Feel_the_Burn_mayhem_augment.webp" },
  { id: 22, name: "精怪魔法", description: "精怪魔法海克斯大乱斗强化符文攻略 - 你的终极技能的伤害会对敌人造成持续2秒的变形效果。 胜率：47.29%，登场率：4.90%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Fey_Magic_mayhem_augment.webp" },
  { id: 23, name: "最终形态", description: "最终形态海克斯大乱斗强化符文攻略 - 在施放你的终极技能时，获得持续10秒的50%最大生命值护盾、20%全能吸血和30%额外移动速度。(20秒冷却时间) 胜率：52.17%，登场率：17.31%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Final_Form_mayhem_augment.webp" },
  { id: 24, name: "砍伤", description: "砍伤海克斯大乱斗强化符文攻略 - 获得50%攻击速度。攻击造成 20-40/10-20（+25%/20%额外护甲）真实伤害 命中。 胜率：50.56%，登场率：8.43%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Gash_mayhem_augment.webp" },
  { id: 25, name: "巨人杀手", description: "巨人杀手海克斯大乱斗强化符文攻略 - 体型变小，获得30%移动速度，并基于敌方英雄体型大于你的程度造成10%到30%额外伤害。 胜率：59.44%，登场率：42.72%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Giant_Slayer_mayhem_augment.webp" },
  { id: 26, name: "玻璃大炮", description: "玻璃大炮海克斯大乱斗强化符文攻略 - 减少30%最大生命值。造成15%额外真实伤害。 胜率：46.69%，登场率：6.00%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Glass_Cannon_mayhem_augment.webp" },
  { id: 27, name: "夺金", description: "夺金海克斯大乱斗强化符文攻略 - 用攻击或技能对一个英雄造成伤害时会造成额外50-150(基于等级) +40%额外AD +20%AP魔法伤害，并为你提供30金币和持续1.5秒的25%移动速度(每个英雄有30秒冷却时间)。 胜率：51.19%，登场率：5.95%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Goldrend_mayhem_augment.webp" },
  { id: 28, name: "歌利亚巨人", description: "歌利亚巨人海克斯大乱斗强化符文攻略 - 体型变大，获得35%生命值和15%适应之力。 胜率：56.60%，登场率：32.47%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Goliath_mayhem_augment.webp" },
  { id: 29, name: "男爵之手", description: "男爵之手海克斯大乱斗强化符文攻略 - 获得33%适应之力，附近友方小兵都获得极大增强。 胜率：52.24%，登场率：1.46%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Hand_of_Baron_mayhem_augment.webp" },
  { id: 30, name: "当心小蛋糕！", description: "当心小蛋糕！海克斯大乱斗强化符文攻略 - 周期性地出现一个小蛋糕快速越过整个大桥，接住小蛋糕的英雄会获得15金币，其与其附近的友军回复50-250(+5-20%(基于等级)已损失生命值)生命值，但是会减速50%，持续0.5秒。你的小蛋糕每治疗1000生命值，就会提供200金币…", tier: "prismatic", image: "https://arammayhem.com/augments/Heads_Up_Cupcake!_mayhem_augment.webp" },
  { id: 31, name: "神圣雪球", description: "神圣雪球海克斯大乱斗强化符文攻略 - 你的雪球获得100技能急速，使用雪球冲刺后获得1秒的免疫伤害 胜率：47.19%，登场率：9.90%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Holy_Snowball_mayhem_augment.webp" },
  { id: 32, name: "小猫咪找妈妈", description: "小猫咪找妈妈海克斯大乱斗强化符文攻略 - 站在一个友军的附近并将其标记为你的妈妈。 当朝着妈妈移动时，获得37.5%移动速度。当靠近你的妈妈时，获得75%移动速度、50%治疗和护盾强度。 胜率：49.47%，登场率：1.66%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/I'm_a_Baby_Kitty_Where_is_Mama_mayhem_augment.webp" },
  { id: 33, name: "炼狱导管", description: "炼狱导管海克斯大乱斗强化符文攻略 - 技能会施加一层可无限叠加的灼烧，每秒造成1.2 - 12 (基于等级) (+ 2.8 %额外AD) (+ 1.2 % AP) 点魔法伤害。 灼烧效果会降低你各基础技能的冷却时间0.08秒。 胜率：57.97%，登场率：28.25%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Infernal_Conduit_mayhem_augment.webp" },
  { id: 34, name: "无限循环往复", description: "无限循环往复海克斯大乱斗强化符文攻略 - 获得60技能急速，参与击杀额外获得3技能急速 胜率：57.42%，登场率：18.78%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Infinite_Recursion_mayhem_augment.webp" },
  { id: 35, name: "珠光护手", description: "珠光护手海克斯大乱斗强化符文攻略 - 你的技能可以造成暴击，造成145%总伤害。获得25%(+ 4.5% AP)%暴击几率。 胜率：58.93%，登场率：49.60%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Jeweled_Gauntlet_mayhem_augment.webp" },
  { id: 36, name: "尊我为王", description: "尊我为王海克斯大乱斗强化符文攻略 - 当你第一次携带一件传说级装备并乘坐敌人的传送门时，你会加冕为王，升级你的装备并获得一个随机棱彩阶强化符文。 胜率：52.78%，登场率：12.02%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/King_Me_mayhem_augment.webp" },
  { id: 37, name: "激光治疗", description: "激光治疗海克斯大乱斗强化符文攻略 - 施放一个持续2.5秒的治疗激光，治疗友军200-550(基于等级) +70%AP +50%额外生命值 生命值，对敌人造成100-350(基于等级) +50%AP魔法伤害并使敌人减速20%。 胜率：49.86%，登场率：6.05%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Laser_Heal_mayhem_augment.webp" },
  { id: 38, name: "科学狂人", description: "科学狂人海克斯大乱斗强化符文攻略 - 在回合开始时，你的体型要么变大(获得@ADAmp*100@%适应之力和@HealthAmp*100@%生命值)要么变小(获得@Haste@技能急速和@MovespeedAmp*100@%移动速度)。 胜率：53.67%，登场率：7.78%。了解哪些英雄最适配该强...", tier: "prismatic", image: "https://arammayhem.com/augments/Mad_Scientist_mayhem_augment.webp" },
  { id: 39, name: "物法皆修", description: "物法皆修海克斯大乱斗强化符文攻略 - 你的每次攻击为你提供6 - 18 法术强度，并且你的每次技能为你提供3 - 9 攻击力 增益可无限叠加并刷新，但有5秒的持续时间。 胜率：51.42%，登场率：14.68%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Master_of_Duality_mayhem_augment.webp" },
  { id: 40, name: "秘术冲拳", description: "秘术冲拳海克斯大乱斗强化符文攻略 - 命中使你的各个技能的冷却时间缩减其1.25秒冷却时间。 胜率：53.60%，登场率：25.60%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Mystic_Punch_mayhem_augment.webp" },
  { id: 41, name: "不祥契约", description: "不祥契约海克斯大乱斗强化符文攻略 - 基于已损失生命值，获得至多75 - 150(基于等级)法术强度，50%移动速度和20%全能吸血。施放技能会消耗你的5%当前生命值。 在30%生命值时获得最大增益。 胜率：49.18%，登场率：7.01%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Ominous_Pact_mayhem_augment.webp" },
  { id: 42, name: "全能龙魂", description: "全能龙魂海克斯大乱斗强化符文攻略 - 获得3个随机龙魂。 胜率：51.00%，登场率：5.06%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Omni_Soul_mayhem_augment.webp" },
  { id: 43, name: "轨道镭射", description: "轨道镭射海克斯大乱斗强化符文攻略 - 在2.5秒后，召唤一道轨道镭射光束落下，造成25%目标最大生命值的真实伤害并在3秒内持续造成共360-600 (基于等级) 的魔法伤害。 每场游戏仅会有一位玩家拥有这个强化符文 胜率：46.67%，登场率：1.15%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/OrbitalLaser_mayhem_augment.webp" },
  { id: 44, name: "潘朵拉的盒子", description: "潘朵拉的盒子海克斯大乱斗强化符文攻略 - 将你的所有强化符文变为随机的棱彩阶强化符文。 胜率：54.80%，登场率：20.29%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/PandorasBox_mayhem_augment.webp" },
  { id: 45, name: "舞会女王", description: "舞会女王海克斯大乱斗强化符文攻略 - 每25秒自动获得一个围绕你的聚光灯，聚光灯会在2.5秒后落下，当它着陆时，获得洛的终极技能，魅惑你碰到的敌人们。 胜率：48.52%，登场率：4.62%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Prom_Queen_mayhem_augment.webp" },
  { id: 46, name: "蛋白粉奶昔", description: "蛋白粉奶昔海克斯大乱斗强化符文攻略 - 获得25%(+35%额外护甲)(+35%额外魔抗)治疗和护盾强度。 胜率：47.90%，登场率：8.71%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Protein_Shake_mayhem_augment.webp" },
  { id: 47, name: "量子计算", description: "量子计算海克斯大乱斗强化符文攻略…", tier: "prismatic", image: "https://arammayhem.com/augments/Quantum_Computing_mayhem_augment.webp" },
  { id: 48, name: "任务：海牛阿福的勇士", description: "任务：海牛阿福的勇士海克斯大乱斗强化符文攻略 - 需求：参与击杀@TakedownsNeeded@次。 奖励：金铲铲 胜率：50.45%，登场率：4.48%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Quest:_Urf's_Champion_mayhem_augment.webp" },
  { id: 49, name: "任务：沃格勒特的巫师帽", description: "任务：沃格勒特的巫师帽海克斯大乱斗强化符文攻略 - 即刻：获得【无用大棒】。 需求：持有【灭世者的死亡之帽】和【中娅沙漏】。 奖励：获得【沃格勒特的巫师帽】。 胜率：53.74%，登场率：15.15%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Quest:_Wooglet's_Witchcap_mayhem_augment.webp" },
  { id: 50, name: "红包", description: "红包海克斯大乱斗强化符文攻略 - 每25-15(基于等级)秒，你的周围随机出现红包，拾取红包可以获得10-18(基于等级)到28-58(基于等级)金币，随机属性，以及持续4秒的150移动速度 胜率：57.66%，登场率：21.84%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Red_Envelopes_mayhem_augment.webp" },
  { id: 51, name: "最万用的瞄准镜", description: "最万用的瞄准镜海克斯大乱斗强化符文攻略 - 获得300攻击距离，如果你是远程英雄则降低至150攻击距离。 胜率：52.60%，登场率：18.37%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Scopiest_Weapons_mayhem_augment.webp" },
  { id: 52, name: "慢炖", description: "慢炖海克斯大乱斗强化符文攻略 - 每一秒，对500码内的敌方英雄们施加一层可无限叠加的灼烧，在5秒的持续时间里每秒造成0.35%最大生命值的伤害。 胜率：57.06%，登场率：17.87%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Slow_Cooker_mayhem_augment.webp" },
  { id: 53, name: "属性叠属性叠属性！", description: "属性叠属性叠属性！海克斯大乱斗强化符文攻略 - 获得5个属性锻造器，有更高几率出现黄金阶和棱彩阶锻造器！ 在你的下一次强化符文选取时，每个栏位获得一次额外的刷新。 胜率：55.95%，登场率：15.74%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Stats_on_Stats_on_Stats!_mayhem_augment.webp" },
  { id: 54, name: "和我一起困在这里", description: "和我一起困在这里海克斯大乱斗强化符文攻略 - 使用你的终极技能时会嘲讽附近的敌人们并提供给你持续2秒的40%伤害减免。 胜率：46.24%，登场率：1.67%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Stuck_In_Here_With_Me_mayhem_augment.webp" },
  { id: 55, name: "战争交响乐", description: "战争交响乐海克斯大乱斗强化符文攻略 - 获得致命节奏和征服者基石符文。 胜率：50.66%，登场率：14.76%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Symphony_of_War_mayhem_augment.webp" },
  { id: 56, name: "踢踏舞", description: "踢踏舞海克斯大乱斗强化符文攻略 - 你的攻击会为你提供@MSPerHit@移动速度。获得相当于你@MSToASConversion*10000@% 移动速度的攻击速度。 增益可无限叠加并刷新，但有@StackDuration@秒的持续时间。…", tier: "prismatic", image: "https://arammayhem.com/augments/Tap_Dancer_mayhem_augment.webp" },
  { id: 57, name: "质变：混沌", description: "质变：混沌海克斯大乱斗强化符文攻略 - 获得2个随机的强化符文。 胜率：59.36%，登场率：30.33%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Transmute:_Chaos_mayhem_augment.webp" },
  { id: 58, name: "扳机炼狱", description: "扳机炼狱海克斯大乱斗强化符文攻略 - 获得悍勇本色。在你达到S评价等级时，自动使用炼狱扳机。悍勇本色 - 使用与前一个不同的技能或攻击对敌人造成伤害时，会获得评价等级 (从F到S)。从每评价等级中获得2.8%-3.5%(基于等级)移动速度。 炼狱扳机…", tier: "prismatic", image: "https://arammayhem.com/augments/Triggered_Inferno_mayhem_augment.webp" },
  { id: 59, name: "精准奇才", description: "精准奇才海克斯大乱斗强化符文攻略 - 在你从700码外对一名敌人造成伤害时， 发射一道精准弹幕，造成100 – 350 (基于等级) (+ 80%额外AD) (+ 70% 法术强度) 魔法伤害。15秒冷却时间。 每场游戏仅会有一位玩家拥有这个强化符文…", tier: "prismatic", image: "https://arammayhem.com/augments/TrueshotProdigy_mayhem_augment.webp" },
  { id: 60, name: "终极唤醒", description: "终极唤醒海克斯大乱斗强化符文攻略 - 你的终极技能获得30技能急速。在施放你的终极技能后，重置你所有基础技能的冷却时间并获得持续15秒的300基础技能急速。(20秒冷却时间) 胜率：48.36%，登场率：7.25%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Ultimate_Awakening_mayhem_augment.webp" },
  { id: 61, name: "终极刷新", description: "终极刷新海克斯大乱斗强化符文攻略 - 在施放终极技能后刷新你的终极技能。(冷却秒冷却时间或阵亡时重置) 胜率：47.23%，登场率：7.42%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Ultimate_Revolution_mayhem_augment.webp" },
  { id: 62, name: "升级：米凯尔的祝福", description: "升级：米凯尔的祝福海克斯大乱斗强化符文攻略 - 【米凯尔的祝福】的冷却时间降低至45秒。获得一个【米凯尔的祝福】。 使用【米凯尔的祝福】的主动效果时，对附近的友军施放一道光波，清除其限制和定身效果，回复150-450(基于等级) +50%AP生命值，并且提供持续3秒的65%韧性。…", tier: "prismatic", image: "https://arammayhem.com/augments/Upgrade_Mikael's_Blessing_mayhem_augment.webp" },
  { id: 63, name: "任务：艾卡西亚的陷落", description: "任务：艾卡西亚的陷落海克斯大乱斗强化符文攻略 - 即刻：获得一个斑比的熔渣并且你可以同时购买两件献祭装备。 需求：持有【日炎圣盾】和【璀璨回响】。 奖励：将【日炎圣盾】和【璀璨回响】组合成【虚空献祭】。 胜率：55.94%，登场率：10.83%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Void_Immolation_mayhem_augment.webp" },
  { id: 64, name: "虚空裂隙", description: "虚空裂隙海克斯大乱斗强化符文攻略 - 用技能对敌人造成伤害时，会制造一道虚空裂痕，持续6秒，如果附近有另一道虚空裂痕，则它们会连接来对它们之间的敌人们造成75-350（+450%穿甲）（+450%法术穿透）魔法伤害，以及持续1秒的99%减速…", tier: "prismatic", image: "https://arammayhem.com/augments/Void_Rift_mayhem_augment.webp" },
  { id: 65, name: "风语者的祝福", description: "风语者的祝福海克斯大乱斗强化符文攻略 - 你的治疗效果和护盾效果还会提升目标30-60的护甲和魔法抗性，这些加成持续3秒。 胜率：51.54%，登场率：4.89%。了解哪些英雄最适配该强化符文。", tier: "prismatic", image: "https://arammayhem.com/augments/Windspeaker's_Blessing_mayhem_augment.webp" },
  { id: 66, name: "全心为你", description: "全心为你海克斯大乱斗强化符文攻略 - 你的治疗和护盾在用在一个友军身上时会变强@HealShieldAmp*100@%。 胜率：49.40%，登场率：4.58%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/All_For_You_mayhem_augment.webp" },
  { id: 67, name: "尖端发明家", description: "尖端发明家海克斯大乱斗强化符文攻略 - 获得60装备急速(相当于37%装备冷却缩减)。 装备急速可缩减所有装备技能的冷却时间%i:cooldown%。 胜率：50.02%，登场率：20.93%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Apex_Inventor_mayhem_augment.webp" },
  { id: 68, name: "超强大脑", description: "超强大脑海克斯大乱斗强化符文攻略 - 获得一个可吸收300%法术强度伤害的护盾，护盾被打破前持续生效。护盾会在阵亡时或每70秒刷新一次。 胜率：53.24%，登场率：12.58%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Big_Brain_mayhem_augment.webp" },
  { id: 69, name: "面包和黄油", description: "面包和黄油海克斯大乱斗强化符文攻略 - 你的Q获得100技能急速。 胜率：50.43%，登场率：18.70%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Bread_And_Butter_mayhem_augment.webp" },
  { id: 70, name: "面包和奶酪", description: "面包和奶酪海克斯大乱斗强化符文攻略 - 你的E获得@EAbilityHaste@技能急速。 胜率：50.14%，登场率：13.83%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Bread_and_Cheese_mayhem_augment.webp" },
  { id: 71, name: "面包和果酱", description: "面包和果酱海克斯大乱斗强化符文攻略 - 你的W获得@WAbilityHaste@技能急速。 胜率：48.65%，登场率：11.33%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Bread_And_Jam_mayhem_augment.webp" },
  { id: 72, name: "星界躯体", description: "星界躯体海克斯大乱斗强化符文攻略 - 获得1500，但你造成的伤害降低10%。 胜率：55.86%，登场率：33.41%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Celestial_Body_mayhem_augment.webp" },
  { id: 73, name: "作弊：我能回城！", description: "作弊：我能回城！海克斯大乱斗强化符文攻略 - 按下【回城】能够回到基地，购买装备并且获得强化符文。 胜率：52.28%，登场率：19.11%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Cheating_mayhem_augment.webp" },
  { id: 74, name: "会心治疗", description: "会心治疗海克斯大乱斗强化符文攻略 - 你的治疗和护盾可以暴击，获得@CritHeal*100@%额外数额的效果。获得20%暴击几率。 胜率：54.99%，登场率：32.37%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Critical_Healing_mayhem_augment.webp" },
  { id: 75, name: "暴击飞弹", description: "暴击飞弹海克斯大乱斗强化符文攻略 - 获得25%暴击率，当你暴击时，会施放1-4道飞弹(基于暴击率)，每道飞弹造成11-40(+7%额外攻击力)(+10%法术强度)魔法伤害 胜率：62.32%，登场率：47.72%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Critical_Missile_mayhem_augment.webp" },
  { id: 76, name: "暴击律动", description: "暴击律动海克斯大乱斗强化符文攻略 - 获得25%暴击几率。你的普攻在暴击时获得可叠加的6%攻击速度。(至多至10层) 胜率：53.46%，登场率：22.54%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Critical_Rhythm_mayhem_augment.webp" },
  { id: 77, name: "黎明使者的坚决", description: "黎明使者的坚决海克斯大乱斗强化符文攻略 - 在跌到@HealthThreshold*100@%生命值以下时，在3秒里持续回复共@HealAmount*100@%最大生命值。（45秒 冷却时间） 胜率：49.78%，登场率：6.28%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Dawnbringer's_Resolve_mayhem_augment.webp" },
  { id: 78, name: "魔鬼之舞", description: "魔鬼之舞海克斯大乱斗强化符文攻略 - 获得迅捷步法和不灭之握基石符文。 - 迅捷步法：攻击和移动会积攒能量层数。在100层时，你的下次攻击会治疗你并提升移动速度。 - 不灭之握：在战斗中每过@GRTriggerTime@秒，你对一个英雄发起的下一次普攻将会造成额外魔法伤害、治疗你、并永久提升你的生命...", tier: "gold", image: "https://arammayhem.com/augments/Demon's_Dance_mayhem_augment.webp" },
  { id: 79, name: "神圣干预", description: "神圣干预海克斯大乱斗强化符文攻略 - 每35秒，召唤护体星星缓慢地降落在你身上。在它着陆时，你和附近的友军们进入2.5秒的免疫伤害状态。 胜率：49.12%，登场率：10.08%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Divine_Intervention_mayhem_augment.webp" },
  { id: 80, name: "捐赠", description: "捐赠海克斯大乱斗强化符文攻略 - 获得2500金币。 胜率：56.74%，登场率：26.48%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Donation_mayhem_augment.webp" },
  { id: 81, name: "双发快射", description: "双发快射海克斯大乱斗强化符文攻略 - 获得25%暴击率，暴击时会额外施加一次命中 胜率：53.29%，登场率：15.96%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Double_Tap_mayhem_augment.webp" },
  { id: 82, name: "虚幻武器", description: "虚幻武器海克斯大乱斗强化符文攻略 - 你的技能可施加命中。每个目标有1秒冷却时间。 胜率：51.90%，登场率：19.91%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Ethereal_Weapon_mayhem_augment.webp" },
  { id: 83, name: "裁决使", description: "裁决使海克斯大乱斗强化符文攻略 - 对生命值低于30%的敌人们多造成10%伤害。在参与击杀后重置你的基础技能。 胜率：59.52%，登场率：56.15%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Executioner_mayhem_augment.webp" },
  { id: 84, name: "最终都市列车", description: "最终都市列车海克斯大乱斗强化符文攻略 - 在你阵亡时，朝击杀你的敌人发动一辆列车，对命中的敌人造成150-750(+50%法术强度)(+65%额外攻击力)(+15%最大生命值)物理伤害。这个列车不会停下。 胜率：51.86%，登场率：18.36%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Final_City_Transit_mayhem_augment.webp" },
  { id: 85, name: "火上浇油", description: "火上浇油海克斯大乱斗强化符文攻略 - 你的攻击还会灼烧敌人，在@BleedDuration@秒的持续时间里每秒持续造成@PercentMaxHPDamagePer5Seconds*20@%最大生命值的魔法伤害。灼烧可无限叠加。 胜率：50.23%，登场率：14.15%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Firebrand_mayhem_augment.webp" },
  { id: 86, name: "有始有终", description: "有始有终海克斯大乱斗强化符文攻略 - 获得先攻和黑暗收割基石符文。此外，你每拥有一个强化符文，即可获得8黑暗收割层数。 胜率：57.12%，登场率：30.38%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/From_Beginning_To_End_mayhem_augment.webp" },
  { id: 87, name: "罪恶快感", description: "罪恶快感海克斯大乱斗强化符文攻略 - 参与击杀后，获得持续4秒的100%移动速度和15%总攻击速度。 胜率：53.03%，登场率：27.08%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Get_Excited!_mayhem_augment.webp" },
  { id: 88, name: "祖母的辣椒油", description: "祖母的辣椒油海克斯大乱斗强化符文攻略 - 施加一个灼烧时，会在附近掉落一个持续5秒的辣椒油池子，站在一个辣椒油池子上每秒会回复60-150(+30x燃烧来源)生命值，并对敌人造成60(+100x燃烧来源)魔法伤害。 胜率：58.24%，登场率：29.79%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Grandma's_Chili_Oil_mayhem_augment.webp" },
  { id: 89, name: "生机迸发", description: "生机迸发海克斯大乱斗强化符文攻略 - 获得【生机迸发】召唤师技能。【生机迸发】会猛然提升你的体型，击飞附近的敌人们并提供300（+20%生命值）最大生命值。 胜率：50.80%，登场率：8.70%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Growth_Spurt_mayhem_augment.webp" },
  { id: 90, name: "圣火", description: "圣火海克斯大乱斗强化符文攻略 - 你的治疗或护盾会对一个附近的敌人施加一层无限叠加的灼烧，在@BurnDuration@秒里持续造成至多@BurnPercentMax*100@%最大生命值的魔法伤害(最小值：@BurnPercentMin*100@%)。…", tier: "gold", image: "https://arammayhem.com/augments/Holy_Fire_mayhem_augment.webp" },
  { id: 91, name: "不动如山", description: "不动如山海克斯大乱斗强化符文攻略 - 获余震和冰川增幅基石符文。 胜率：48.71%，登场率：9.21%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Impassable_mayhem_augment.webp" },
  { id: 92, name: "关键暴击", description: "关键暴击海克斯大乱斗强化符文攻略 - 获得20%暴击几率。 胜率：49.65%，登场率：12.83%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/It's_Critical_mayhem_augment.webp" },
  { id: 93, name: "杀戮时间到了", description: "杀戮时间到了海克斯大乱斗强化符文攻略 - 在施放你的终极技能后，将所有敌人打上死亡标记。这个标记会将你对其造成的@DamageStorePercentage*100@%伤害储存起来，然后在@MarkDuration@秒后引爆，造成已储存的伤害(冷却秒冷却时间)。…", tier: "gold", image: "https://arammayhem.com/augments/It's_Killing_Time_mayhem_augment.webp" },
  { id: 94, name: "基石法师", description: "基石法师海克斯大乱斗强化符文攻略 - 获得召唤：艾黎和奥术彗星基石符文。 胜率：51.01%，登场率：11.67%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Keystone_Conjurer_mayhem_augment.webp" },
  { id: 95, name: "闪电打击", description: "闪电打击海克斯大乱斗强化符文攻略 - 获得40%总攻击速度。 在2.5攻击次数/秒时，造成额外的魔法伤害 命中。 胜率：54.44%，登场率：24.16%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Lightning_Strikes_mayhem_augment.webp" },
  { id: 96, name: "魔法飞弹", description: "魔法飞弹海克斯大乱斗强化符文攻略 - 用一个技能造成伤害时，会对每个被命中的敌人发射3个魔法飞弹，每个魔法飞弹基于飞行距离至多造成1%最大生命值的真实伤害。 胜率：60.87%，登场率：52.69%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Magic_Missile_mayhem_augment.webp" },
  { id: 97, name: "神射法师", description: "神射法师海克斯大乱斗强化符文攻略 - 你的攻击造成相当于你75%法术强度的额外物理伤害。 胜率：51.73%，登场率：22.14%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Marksmage_mayhem_augment.webp" },
  { id: 98, name: "仆从大师", description: "仆从大师海克斯大乱斗强化符文攻略 - 你的召唤物获得@MinionSizeIncrease*100@%体型提升、生命值和伤害。 胜率：50.47%，登场率：2.20%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Minionmancer_mayhem_augment.webp" },
  { id: 99, name: "夜狩", description: "夜狩海克斯大乱斗强化符文攻略 - 在对敌人造成伤害的3秒内参与击杀该敌人会使你进入1.5秒的隐身状态。 胜率：48.30%，登场率：15.53%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Nightstalking_mayhem_augment.webp" },
  { id: 100, name: "回力OK镖", description: "回力OK镖海克斯大乱斗强化符文攻略 - 每@BaseCooldown@秒朝着一个附近的敌人自动施放投掷一个回力镖，对命中的敌人们造成40 – 200 (基于等级) (+ 22%额外AD) (+ 15% AP)自适应伤害。 胜率：50.69%，登场率：7.40%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Ok_Boomerang_mayhem_augment.webp" },
  { id: 101, name: "狂徒豪气", description: "狂徒豪气海克斯大乱斗强化符文攻略 - 你的冲刺、跳跃、闪烁或传送类技能会为你提供12点额外护甲和12点额外魔法抗性，持续15秒，最多可叠加至5层(共提供60点双抗)。当前层数会在状态栏中显示。 胜率：52.31%，登场率：10.82%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Outlaw's_Grit_mayhem_augment.webp" },
  { id: 102, name: "溢流", description: "溢流海克斯大乱斗强化符文攻略 - 你的法力值消耗翻倍。你的技能的治疗效果、护盾效果和伤害的效能提升10% （每 100最大法力值+ 0.5 % ）。 胜率：54.20%，登场率：26.94%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Overflow_mayhem_augment.webp" },
  { id: 103, name: "坚韧", description: "坚韧海克斯大乱斗强化符文攻略 - 获得250%基础生命回复，在低于25%生命值时提升至10%基础生命回复。 胜率：52.65%，登场率：22.71%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Perseverance_mayhem_augment.webp" },
  { id: 104, name: "超凡邪恶", description: "超凡邪恶海克斯大乱斗强化符文攻略 - 在你用技能命中敌人时永久获得1法术强度。 如果是作为你的第二个强化符文，则自带40法术强度。 胜率：60.78%，登场率：43.62%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Phenomenal_Evil_mayhem_augment.webp" },
  { id: 105, name: "弹球", description: "弹球海克斯大乱斗强化符文攻略 - 你的雪球获得50技能急速，造成额外100-500(基于等级)真实伤害，并且可以从墙上反弹，每次反弹都会提升它25%体型，20%伤害，并且缩短它30%冷却时间 胜率：50.94%，登场率：19.66%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Pinball_mayhem_augment.webp" },
  { id: 106, name: "魄罗爆破手", description: "魄罗爆破手海克斯大乱斗强化符文攻略 - 你周期性地召集魄罗，最多5只，攻击和技能会发射所有魄罗，每个魄罗造成3%最大生命值的真实伤害并击退敌人 胜率：53.94%，登场率：21.82%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Poro_Blaster_mayhem_augment.webp" },
  { id: 107, name: "任务：钢化你心", description: "任务：钢化你心海克斯大乱斗强化符文攻略 - 需求：持有【心之钢】且层数在300层或以上。 奖励：将你当前及后续的心之钢层数乘以3。 胜率：61.59%，登场率：39.27%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Quest:_Steel_Your_Heart_mayhem_augment.webp" },
  { id: 108, name: "古式佳酿", description: "古式佳酿海克斯大乱斗强化符文攻略 - 使用一个技能时会回复5 – 60 (基于等级)（+ 1%最大生命值）点生命值。 胜率：52.48%，登场率：19.25%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Rabble_Rousing_mayhem_augment.webp" },
  { id: 109, name: "循环往复", description: "循环往复海克斯大乱斗强化符文攻略 - 获得60技能急速。 胜率：53.94%，登场率：25.61%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Recursion_mayhem_augment.webp" },
  { id: 110, name: "无休回复", description: "无休回复海克斯大乱斗强化符文攻略 - 你每移动1000码距离就会回复20-120(基于等级)（+0.1% 最大生命值）的生命值。 胜率：51.75%，登场率：7.58%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Restless_Restoration_mayhem_augment.webp" },
  { id: 111, name: "更万用的瞄准镜", description: "更万用的瞄准镜海克斯大乱斗强化符文攻略 - 获得200攻击距离，如果你是远程英雄则降低至100攻击距离。 胜率：56.02%，登场率：33.28%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Scopier_Weapons_mayhem_augment.webp" },
  { id: 112, name: "炽烈黎明", description: "炽烈黎明海克斯大乱斗强化符文攻略 - 你的技能会标记敌人，使其在被你的友军的下一个攻击或技能命中时会受到额外40-200(基于等级)魔法伤害。 胜率：47.92%，登场率：3.52%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Searing_Dawn_mayhem_augment.webp" },
  { id: 113, name: "缩小引擎", description: "缩小引擎海克斯大乱斗强化符文攻略 - 每次参与击杀敌方英雄会让你变小4%，获得10技能急速和2%移动速度，死亡时损失65%层数 胜率：62.17%，登场率：47.74%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Shrink_Engine_mayhem_augment.webp" },
  { id: 114, name: "缩小射线", description: "缩小射线海克斯大乱斗强化符文攻略 - 你的攻击会对敌人造成持续3秒的@DamageReduction*100@%伤害削减效果。 胜率：48.04%，登场率：12.74%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Shrink_Ray_mayhem_augment.webp" },
  { id: 115, name: "老练狙神", description: "老练狙神海克斯大乱斗强化符文攻略 - 用一个非终极技能命中一个@SnipeDistance@码距离外的敌人时，返还该技能80%冷却时间(周期性技能返还65%)。 胜率：51.42%，登场率：21.25%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Skilled_Sniper_mayhem_augment.webp" },
  { id: 116, name: "一板一眼", description: "一板一眼海克斯大乱斗强化符文攻略 - 获得25攻击力。你的攻击速度变为@StaticRatio@。所有额外攻击速度会被转化为攻击力。(每1%攻速转为1攻击力)。 胜率：51.23%，登场率：17.16%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Slow_And_Steady_mayhem_augment.webp" },
  { id: 117, name: "雪球扭蛋机", description: "雪球扭蛋机海克斯大乱斗强化符文攻略 - 雪球获得100技能急速。在使用雪球后，随机对自身施放一个增益型的召唤师技能并对你的目标施放一个减益型的召唤师技能。在使用雪球突进后，再次对自身施放该增益型的召唤师技能。 如果你没有雪球，获得一个雪球。…", tier: "prismatic", image: "https://arammayhem.com/augments/Snowball_Roulette_mayhem_augment.webp" },
  { id: 118, name: "升级：雪球", description: "升级：雪球海克斯大乱斗强化符文攻略 - 你的雪球获得100技能急速。 击中时会产生一片区域，使其中的敌人受到50% +6%/100AP减速效果，以及在2秒的持续时间里每秒造成100 +100%额外AD +60%AP魔法伤害(总计200 +200%额外AD +120%AP魔法伤害)。…", tier: "gold", image: "https://arammayhem.com/augments/Snowball_Upgrade_mayhem_augment.webp" },
  { id: 119, name: "咏叹奏鸣", description: "咏叹奏鸣海克斯大乱斗强化符文攻略 - 每10秒交替自动施放【坚毅咏叹调】和【迅捷奏鸣曲】 胜率：54.56%，登场率：6.12%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Sonata_mayhem_augment.webp" },
  { id: 120, name: "吞噬灵魂", description: "吞噬灵魂海克斯大乱斗强化符文攻略 - 定身一个敌方英雄会获得20最大生命值 胜率：57.71%，登场率：38.59%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Soul_Eater_mayhem_augment.webp" },
  { id: 121, name: "灵魂虹吸", description: "灵魂虹吸海克斯大乱斗强化符文攻略 - 获得@CritChance*100@%暴击几率和作用于暴击的@HealPercentage*100@%生命偷取。 胜率：52.99%，登场率：18.04%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Soul_Siphon_mayhem_augment.webp" },
  { id: 122, name: "心灵净化", description: "心灵净化海克斯大乱斗强化符文攻略 - 参与击杀英雄时，在其上方产生一次爆炸，对敌人造成相当于其15%当前生命值的伤害。随后它会持续存在1.5秒，对敌人造成60%减速效果。 胜率：50.84%，登场率：22.96%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Spiritual_Purification_mayhem_augment.webp" },
  { id: 123, name: "属性叠属性！", description: "属性叠属性！海克斯大乱斗强化符文攻略 - 获得4个属性锻造器，有更高几率出现黄金阶和棱彩阶锻造器！ 胜率：62.21%，登场率：34.89%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Stats_on_Stats!_mayhem_augment.webp" },
  { id: 124, name: "坦克引擎", description: "坦克引擎海克斯大乱斗强化符文攻略 - 参与击杀时，获得一个层数，使你的体型增大5%并提升5%最大生命值。阵亡时损失65%层数。 胜率：63.34%，登场率：54.44%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Tank_Engine_mayhem_augment.webp" },
  { id: 125, name: "穿针引线", description: "穿针引线海克斯大乱斗强化符文攻略 - 获得@PercentPen*100@%护甲穿透和法术穿透。 胜率：53.68%，登场率：36.33%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Thread_the_Needle_mayhem_augment.webp" },
  { id: 126, name: "质变：棱彩阶", description: "质变：棱彩阶海克斯大乱斗强化符文攻略 - 获得1个随机棱彩阶强化符文。 胜率：66.81%，登场率：58.46%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Transmute:_Prismatic_mayhem_augment.webp" },
  { id: 127, name: "接二连三", description: "接二连三海克斯大乱斗强化符文攻略 - 每第三次攻击，你附带的命中会触发第二次。 胜率：51.22%，登场率：22.16%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Twice_Thrice_mayhem_augment.webp" },
  { id: 128, name: "升级：狂妄", description: "升级：狂妄海克斯大乱斗强化符文攻略 - 参与击杀时，【狂妄】回复你的2.5%最大生命值+ 0.5%*层数的已损失生命值，并且在增益持续时间提供10+5*层数 的移动速度。此外，获得250金币。 胜率：55.70%，登场率：38.46%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Upgrade_Hubris_mayhem_augment.webp" },
  { id: 129, name: "升级：无尽之刃", description: "升级：无尽之刃海克斯大乱斗强化符文攻略 - 获得25%暴击几率和500金币。 装备【无尽之刃】后，你的暴击会随机造成额外暴击伤害，最高可至你暴击几率的50%。 胜率：54.93%，登场率：22.44%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Upgrade_Infinity_Edge_mayhem_augment.webp" },
  { id: 130, name: "升级：耀光", description: "升级：耀光海克斯大乱斗强化符文攻略 - 你的【咒刃】效果造成额外目标最大生命值物理伤害并治疗你自身。此外，获得250金币。 胜率：51.17%，登场率：11.75%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Upgrade_Sheen_mayhem_augment.webp" },
  { id: 131, name: "吸血习性", description: "吸血习性海克斯大乱斗强化符文攻略 - 你不再能够被友军治疗或获得任何生命回复。获得30%全能吸血。 胜率：65.55%，登场率：63.60%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Vampirism_mayhem_augment.webp" },
  { id: 132, name: "易损", description: "易损海克斯大乱斗强化符文攻略 - 你的装备效果和持续伤害效果可以暴击来造成40%额外伤害。获得20%暴击几率。 胜率：54.64%，登场率：29.11%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/Vulnerability_mayhem_augment.webp" },
  { id: 133, name: "急急小子", description: "急急小子海克斯大乱斗强化符文攻略 - 获得移动速度，相当于你的@AbilityHasteToMSConversion*100@%技能急速。 胜率：49.75%，登场率：6.09%。了解哪些英雄最适配该强化符文。", tier: "gold", image: "https://arammayhem.com/augments/With_Haste_mayhem_augment.webp" },
  { id: 134, name: "坚若磐石", description: "坚若磐石海克斯大乱斗强化符文攻略 - 每当你定身或缚地一个敌人时，获得持续10秒的2-10(基于等级)护甲或者魔抗。至多至10 层。 胜率：48.23%，登场率：9.28%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Adamant_mayhem_augment.webp" },
  { id: 135, name: "物理转魔法", description: "物理转魔法海克斯大乱斗强化符文攻略 - 将额外攻击力转化为法术强度，并获得15%法术强度。 胜率：57.09%，登场率：40.94%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/ADAPt_mayhem_augment.webp" },
  { id: 136, name: "大力", description: "大力海克斯大乱斗强化符文攻略 - 获得@ADAmp*100@%攻击力。 胜率：53.36%，登场率：14.66%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Blunt_Force_mayhem_augment.webp" },
  { id: 137, name: "霸符兄弟", description: "霸符兄弟海克斯大乱斗强化符文攻略 - 你获得余烬之冠和洞悉之冠。 余烬之冠：普攻会灼烧和减速敌方英雄。在非战斗状态下，治疗你的一部分最大生命值。 洞悉之冠：获得技能急速，并且每秒回复法力值和能量值。 胜率：55.12%，登场率：18.86%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Buff_Buddies_mayhem_augment.webp" },
  { id: 138, name: "砸开那颗蛋", description: "砸开那颗蛋海克斯大乱斗强化符文攻略 - 护盾过期后会爆炸，对周围敌人造成护盾值等量魔法伤害 胜率：49.35%，登场率：1.54%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Crack_Open_That_Egg_mayhem_augment.webp" },
  { id: 139, name: "由暴生急", description: "由暴生急海克斯大乱斗强化符文攻略 - 每拥有1%暴击率就会获得0.4技能急速 胜率：47.80%，登场率：6.47%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Crit_'n_Cast_mayhem_augment.webp" },
  { id: 140, name: "灵巧", description: "灵巧海克斯大乱斗强化符文攻略 - 获得60%攻击速度。 胜率：57.45%，登场率：38.03%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Deft_mayhem_augment.webp" },
  { id: 141, name: "俯冲轰炸", description: "俯冲轰炸海克斯大乱斗强化符文攻略 - 在你阵亡时爆炸，对附近的敌人们造成目标@PercentMaxHPDamage*100@%最大生命值的真实伤害。 胜率：55.24%，登场率：21.90%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Dive_Bomber_mayhem_augment.webp" },
  { id: 142, name: "唯快不破", description: "唯快不破海克斯大乱斗强化符文攻略 - 你每比目标多10移动速度，则对其多造成@BonusDamagePerMSDifference*1000@%额外伤害。 胜率：51.60%，登场率：4.90%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Don't_Blink_mayhem_augment.webp" },
  { id: 143, name: "侵蚀", description: "侵蚀海克斯大乱斗强化符文攻略 - 对敌人造成伤害时会施加一层持续3秒的5%护甲和魔法抗性击碎效果，至多在6层时击碎30%。 胜率：52.05%，登场率：11.55%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Erosion_mayhem_augment.webp" },
  { id: 144, name: "魔法转物理", description: "魔法转物理海克斯大乱斗强化符文攻略 - 将法术强度转化为额外攻击力，并获得15%攻击力。 胜率：54.60%，登场率：26.46%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/escAPADe_mayhem_augment.webp" },
  { id: 145, name: "逃跑计划", description: "逃跑计划海克斯大乱斗强化符文攻略 - 在降至35%生命值时，获得持续衰减的65%最大生命值护盾、持续衰减的150%移动速度和持续衰减的缩小效果。(75秒冷却时间) 胜率：55.60%，登场率：17.30%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Escape_Plan_mayhem_augment.webp" },
  { id: 146, name: "火狐", description: "火狐海克斯大乱斗强化符文攻略 - 周期性的自动施放阿狸的W技能，为你提供40%移动速度，在2秒内衰减，并生成三个围绕自身的狐火，狐火造成35(+25%额外攻击力+25%法术强度)自适应伤害，同一个目标被多个狐火命中时，额外的狐火只造成30%伤害，7秒冷却时间…", tier: "silver", image: "https://arammayhem.com/augments/FireFox_mayhem_augment.webp" },
  { id: 147, name: "急救用具", description: "急救用具海克斯大乱斗强化符文攻略 - 获得@HealShieldAmp*100@%治疗和护盾强度。 胜率：50.88%，登场率：15.46%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/First-Aid_Kit_mayhem_augment.webp" },
  { id: 148, name: "闪闪现现", description: "闪闪现现海克斯大乱斗强化符文攻略 - 获得第二个【闪现】召唤师技能和70召唤师技能急速。 胜率：46.84%，登场率：0.11%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Flash_2_mayhem_augment.webp" },
  { id: 149, name: "闪光弹", description: "闪光弹海克斯大乱斗强化符文攻略 - 你在【闪现】时会在你周围引发爆炸，造成70 - 240 (基于等级) (+ 70% AD) (+ 60% AP) 魔法伤害和持续@SlowDuration@秒的@SlowAmount*100@%减速。每次阵亡时重置闪现。…", tier: "silver", image: "https://arammayhem.com/augments/Flashbang_mayhem_augment.webp" },
  { id: 150, name: "冰霜 幽灵", description: "冰霜 幽灵海克斯大乱斗强化符文攻略 - 每冷却秒，自动施放@RootDuration@秒禁锢给附近的敌人们。 胜率：50.49%，登场率：12.74%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Frost_Wraith_mayhem_augment.webp" },
  { id: 151, name: "渴血", description: "渴血海克斯大乱斗强化符文攻略 - 获得15%全能吸血。 胜率：59.35%，登场率：48.05%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Goredrink_mayhem_augment.webp" },
  { id: 152, name: "恶趣味", description: "恶趣味海克斯大乱斗强化符文攻略 - 定身或缚地敌方英雄时回复10-150(基于等级)（+1.5%最大生命值）生命值。 胜率：51.18%，登场率：12.47%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Guilty_Pleasure_mayhem_augment.webp" },
  { id: 153, name: "帽上加帽", description: "帽上加帽海克斯大乱斗强化符文攻略 - 头戴式装备和帽子提供15法术强度和8魔法抗性。 帽子饮品提供8法术强度和4魔法抗性。 胜率：52.30%，登场率：19.33%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Hat_on_a_Hat_mayhem_augment.webp" },
  { id: 154, name: "重量级打击手", description: "重量级打击手海克斯大乱斗强化符文攻略 - 你的攻击造成相当于你4%最大生命值的额外物理伤害。 胜率：57.61%，登场率：29.81%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Heavy_Hitter_mayhem_augment.webp" },
  { id: 155, name: "海克斯科技龙魂", description: "海克斯科技龙魂海克斯大乱斗强化符文攻略 - 周期性地使你的下一个伤害型技能或攻击触发一道闪电爆裂，连锁穿过敌人以造成伤害和减速。 胜率：50.19%，登场率：8.14%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Hextech_Soul_mayhem_augment.webp" },
  { id: 156, name: "家园卫士", description: "家园卫士海克斯大乱斗强化符文攻略 - 获得100%移动速度，在受到伤害后失效3秒。 胜率：53.30%，登场率：9.41%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Homeguard_mayhem_augment.webp" },
  { id: 157, name: "冰寒", description: "冰寒海克斯大乱斗强化符文攻略 - 你的减速效果可使移动速度降低额外的100。 胜率：53.92%，登场率：25.64%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Ice_Cold_mayhem_augment.webp" },
  { id: 158, name: "炼狱龙魂", description: "炼狱龙魂海克斯大乱斗强化符文攻略 - 你获得炼狱龙魂，使用技能或攻击命中敌人时造成额外伤害。 胜率：51.06%，登场率：21.63%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Infernal_Soul_mayhem_augment.webp" },
  { id: 159, name: "注魔", description: "注魔海克斯大乱斗强化符文攻略 - 攻击会消耗2.5%最大法力值，造成相当于3.5%最大法力值的魔法伤害，该伤害可以暴击 胜率：49.93%，登场率：7.86%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Juiced_mayhem_augment.webp" },
  { id: 160, name: "杀意翻涌", description: "杀意翻涌海克斯大乱斗强化符文攻略 - 朝着生命值低于40%的敌方英雄时获得100%移动速度。 胜率：49.45%，登场率：8.57%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Kill_Secured_mayhem_augment.webp" },
  { id: 161, name: "练腿日", description: "练腿日海克斯大乱斗强化符文攻略 - 获得50移动速度和40%减速抗性。 胜率：52.11%，登场率：12.66%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Leg_Day_mayhem_augment.webp" },
  { id: 162, name: "点亮他们！", description: "点亮他们！海克斯大乱斗强化符文攻略 - 每第4次攻击造成额外44 – 320 (基于等级) (+ 140%额外AD) (+ 76% AP) 魔法伤害。 胜率：54.83%，登场率：29.18%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Light_'em_Up!_mayhem_augment.webp" },
  { id: 163, name: "强力护盾", description: "强力护盾海克斯大乱斗强化符文攻略 - 当你获得护盾时，获得%i:miniAdaptiveForce%40-100(基于等级)适应之力，持续3秒。(5秒冷却时间) 胜率：47.80%，登场率：6.17%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Mighty_Shield_mayhem_augment.webp" },
  { id: 164, name: "由心及物", description: "由心及物海克斯大乱斗强化符文攻略 - 使你的最大生命值提升，数额相当于你一半的法力值。 胜率：56.64%，登场率：27.44%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Mind_to_Matter_mayhem_augment.webp" },
  { id: 165, name: "山脉龙魂", description: "山脉龙魂海克斯大乱斗强化符文攻略 - 你获得山脉龙魂，在脱离战斗之后获得一个持续一小段时间的护盾。 胜率：48.70%，登场率：7.33%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/MountainSoul_mayhem_augment.webp" },
  { id: 166, name: "海洋龙魂", description: "海洋龙魂海克斯大乱斗强化符文攻略 - 获得【海洋龙魂】，在对敌方英雄造成伤害后提供高额的生命和法力回复。 胜率：54.67%，登场率：16.13%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Ocean_Soul_mayhem_augment.webp" },
  { id: 167, name: "吵闹鬼", description: "吵闹鬼海克斯大乱斗强化符文攻略 - 获得【吵闹鬼】召唤师技能。 吵闹鬼会同时施放召唤师技能【屏障】和【幽灵疾步】。 胜率：47.57%，登场率：2.48%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Poltergeist_mayhem_augment.webp" },
  { id: 168, name: "纯粹主义者 - 术师", description: "纯粹主义者 - 术师海克斯大乱斗强化符文攻略 - 获得10%冷却减缩，你的所有攻速转换为技能急速每1%攻速转换为0.65技能急速 胜率：48.58%，登场率：7.71%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Purist_-_Caster_mayhem_augment.webp" },
  { id: 169, name: "退敌力场", description: "退敌力场海克斯大乱斗强化符文攻略 - 在你跌下@HealthThreshold2*100@%生命值时，附近的敌人们会被击退并对其施加持续1.5秒的90%减速。 胜率：46.36%，登场率：4.75%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Repulsor_mayhem_augment.webp" },
  { id: 170, name: "万用瞄准镜", description: "万用瞄准镜海克斯大乱斗强化符文攻略 - 获得100攻击距离，如果你是远程英雄则降低至50攻击距离。 胜率：51.74%，登场率：22.50%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Scoped_Weapons_mayhem_augment.webp" },
  { id: 171, name: "自我毁灭", description: "自我毁灭海克斯大乱斗强化符文攻略 - 每25秒，会有一个炸弹附在你身上。在@BombDelay@秒后，它会爆炸，造成20%目标最大生命值的真实伤害并击飞附近的敌人们。 胜率：51.85%，登场率：19.23%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Self_Destruct_mayhem_augment.webp" },
  { id: 172, name: "暗影疾奔", description: "暗影疾奔海克斯大乱斗强化符文攻略 - 在使用一个冲刺、跳跃、闪烁或传送类技能或离开潜行状态之后，获得持续3秒的100移动速度。 胜率：55.42%，登场率：21.49%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Shadow_Runner_mayhem_augment.webp" },
  { id: 173, name: "扇巴掌", description: "扇巴掌海克斯大乱斗强化符文攻略 - 每当你定身或缚地一个敌人时，获得一层可叠加的20 适应之力。阵亡时损失50%层数。 胜率：63.09%，登场率：58.76%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Slap_Around_mayhem_augment.webp" },
  { id: 174, name: "天音爆", description: "天音爆海克斯大乱斗强化符文攻略 - 在为你的友军提供增益效果、治疗效果或护盾效果时，会对其附近的敌人造成30 - 150(基于等级)真实伤害和持续2秒的30%减速。 胜率：50.23%，登场率：4.42%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Sonic_Boom_mayhem_augment.webp" },
  { id: 175, name: "速度恶魔", description: "速度恶魔海克斯大乱斗强化符文攻略 - 用技能伤害敌方英雄会获得350移动速度，在2秒内衰减 胜率：54.25%，登场率：30.33%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Speed_Demon_mayhem_augment.webp" },
  { id: 176, name: "转得我眩晕了", description: "转得我眩晕了海克斯大乱斗强化符文攻略 - 将一个召唤师技能替换为骄行荡寇。 骄行荡寇发射一根钩爪，吸附在地形上，在此之后，你可以再次施放来绕着它摆荡。在摆荡状态下，自动攻击相距最近的那个敌人。在与一个敌方英雄碰撞或再次施放时结束摆荡。 胜率：44.82%，登场率：2.04%。了解哪些英雄最适配该强化...", tier: "silver", image: "https://arammayhem.com/augments/Spin_Me_Right_Round_mayhem_augment.webp" },
  { id: 177, name: "旋转至胜", description: "旋转至胜海克斯大乱斗强化符文攻略 - 你的旋转类技能获得@SpinHaste@技能急速并且多造成@SpinDamageAmp*100@%伤害！ 胜率：51.21%，登场率：5.78%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Spin_To_Win_mayhem_augment.webp" },
  { id: 178, name: "叠角龙", description: "叠角龙海克斯大乱斗强化符文攻略 - 在你获得一个技能的永久层数时，多获得75%！ 胜率：52.68%，登场率：0.71%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/StackosaurusRex_mayhem_augment.webp" },
  { id: 179, name: "属性！", description: "属性！海克斯大乱斗强化符文攻略 - 获得3个属性锻造器 胜率：59.80%，登场率：29.47%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Stats!_mayhem_augment.webp" },
  { id: 180, name: "快中求稳", description: "快中求稳海克斯大乱斗强化符文攻略 - 在冲刺或闪烁后，获得持续2秒的65-290(基于等级)(+65% 额外AD)(+26% AP)护盾值。 (5秒冷却时间) 胜率：54.00%，登场率：13.99%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Swift_and_Safe_mayhem_augment.webp" },
  { id: 181, name: "会心防御", description: "会心防御海克斯大乱斗强化符文攻略 - 你可以使用你的暴击几率(最大50%几率)来进行会心防御，使你有一定几率来使所受伤害降低20%。获得25%暴击几率。 胜率：52.76%，登场率：13.40%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Tank_It_Or_Leave_It_mayhem_augment.webp" },
  { id: 182, name: "残暴之力", description: "残暴之力海克斯大乱斗强化符文攻略 - 获得@AD@攻击力、@AbilityHaste@技能急速和@Lethality@穿甲。 胜率：50.32%，登场率：17.57%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/The_Brutalizer_mayhem_augment.webp" },
  { id: 183, name: "折磨者", description: "折磨者海克斯大乱斗强化符文攻略 - 定身或缚地敌方英雄时还会施加一层灼烧，在@BleedDuration@秒的持续时间里每秒持续造成@PercentMaxHPDamagePer5Seconds*20@%最大生命值的魔法伤害。 这个灼烧可无限叠加。…", tier: "silver", image: "https://arammayhem.com/augments/Tormentor_mayhem_augment.webp" },
  { id: 184, name: "双生火焰", description: "双生火焰海克斯大乱斗强化符文攻略 - 技能会发射1-4个飞弹(基于暴击率)，每个飞弹造成10-30(基于等级)(+7%额外攻击力+7%法术强度)魔法伤害，获得15%暴击几率 胜率：54.13%，登场率：28.94%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Twin_Fire_mayhem_augment.webp" },
  { id: 185, name: "台风", description: "台风海克斯大乱斗强化符文攻略 - 你的攻击会对一个额外目标发射一根弩箭，这个弩箭会造成削减过的伤害并施加命中。 胜率：54.23%，登场率：34.11%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Typhoon_mayhem_augment.webp" },
  { id: 186, name: "终极不可阻挡", description: "终极不可阻挡海克斯大乱斗强化符文攻略 - 在你使用你的终极技能后，你获得持续@UnstoppableDuration@秒的控制免疫。 (冷却秒冷却时间)。 胜率：48.01%，登场率：9.78%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Ultimate_Unstoppable_mayhem_augment.webp" },
  { id: 187, name: "升级：收集者", description: "升级：收集者海克斯大乱斗强化符文攻略 - 使用【收集者】的被动处决敌人时的处决阈值提升@ExecutionInc*100@%，并且提供额外@UpgradedGoldAmount@金币。 获得250金币。 胜率：55.79%，登场率：37.14%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Upgrade_Collector_mayhem_augment.webp" },
  { id: 188, name: "升级：弯刀", description: "升级：弯刀海克斯大乱斗强化符文攻略 - 【幽魂弯刀】和【求生索】的冷却时间降低至@UpgradeCD@秒。主动效果激活时，获得@DamageAmp*100@%伤害增幅。 胜率：43.76%，登场率：0.22%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Upgrade_Cutlass_mayhem_augment.webp" },
  { id: 189, name: "升级：献祭", description: "升级：献祭海克斯大乱斗强化符文攻略 - 【璀璨回响】和【日炎圣盾】每当有目标受到【献祭】效果影响时，提供@GoldPerTick@ 金币 。获得250金币。 胜率：53.42%，登场率：16.72%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Upgrade_Immolate_mayhem_augment.webp" },
  { id: 190, name: "升级：荆棘之甲", description: "升级：荆棘之甲海克斯大乱斗强化符文攻略 - 脱离战斗20-5秒后，你的棘刺背心或者荆棘之甲会获得一个外壳，反弹50-250(+12%最大生命值)(+30%护甲)(+30%魔抗)伤害 胜率：55.28%，登场率：11.93%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Upgrade_Thornmail_mayhem_augment.webp" },
  { id: 191, name: "升级：中娅", description: "升级：中娅海克斯大乱斗强化符文攻略 - 升级你的【探索者的护臂】、【沃格勒特的巫师帽】和【中娅沙漏】，使你能够在静滞效果期间移动，并在静滞期间获得50%额外移动速度。此外，【中娅沙漏】的静滞冷却时间降低至45秒。 胜率：53.11%，登场率：19.88%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Upgrade_Zhonya's_mayhem_augment.webp" },
  { id: 192, name: "负重爆气", description: "负重爆气海克斯大乱斗强化符文攻略 - 使用技能对敌方英雄造成伤害会为你提供持续6秒的爆气层数（最大：6）。 每层爆气可以使你的各个非终极技能的冷却时间转速加快2.5%，在6层时提升至5%。 胜率：55.14%，登场率：37.20%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Weighted_Popoffs_mayhem_augment.webp" },
  { id: 193, name: "刃下生风", description: "刃下生风海克斯大乱斗强化符文攻略 - 从每1点固定护甲穿透和法术穿透中获得1.5移动速度。每拥有10%百分比护甲穿透和法术穿透，就获得@PercentPenConversion@移动速度。 胜率：49.72%，登场率：9.25%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Wind_Beneath_Blade_mayhem_augment.webp" },
  { id: 194, name: "巫师式思考", description: "巫师式思考海克斯大乱斗强化符文攻略 - 获得20-80(基于等级)法术强度。 胜率：54.39%，登场率：28.65%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Witchful_Thinking_mayhem_augment.webp" },
  { id: 195, name: "狂热者", description: "狂热者海克斯大乱斗强化符文攻略 - 获得25%暴击率（+0.05%AP）和35%攻击速度（+0.05%AP） 胜率：53.24%，登场率：20.31%。了解哪些英雄最适配该强化符文。", tier: "silver", image: "https://arammayhem.com/augments/Zealot_mayhem_augment.webp" },
];

// 海克斯品质配置
const tierConfig = {
  silver: { name: "银色", color: "#C0C0C0", bgColor: "#2a2a3a" },
  gold: { name: "金色", color: "#FFD700", bgColor: "#3a3a2a" },
  prismatic: { name: "棱彩", color: "#FF69B4", bgColor: "#3a2a3a" }
};

// 导出数据
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { champions, hexAugments, tierConfig };
}
